# Generated by Django 3.2.8 on 2021-12-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.CharField(max_length=7)),
                ('roomCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=7)),
                ('courseName', models.CharField(max_length=50)),
                ('creditHour', models.IntegerField()),
                ('deptcode', models.CharField(max_length=3)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptCode', models.CharField(max_length=3)),
                ('deptName', models.CharField(max_length=50)),
                ('schoolTitle', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyID', models.IntegerField()),
                ('facultyName', models.CharField(max_length=50)),
                ('deptCode', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolTitle', models.CharField(max_length=6)),
                ('schoolName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=7)),
                ('sectionNo', models.IntegerField()),
                ('semester', models.CharField(max_length=6)),
                ('year', models.DateField()),
                ('roomID', models.CharField(max_length=7)),
                ('capacity', models.IntegerField()),
                ('noOfEnrolledStudent', models.IntegerField()),
                ('facultyID', models.IntegerField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('day', models.CharField(max_length=4)),
                ('blocked', models.CharField(max_length=4)),
            ],
        ),
    ]
