# Generated by Django 3.2.9 on 2021-12-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_t',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course_t',
            name='year',
        ),
        migrations.AddField(
            model_name='section_t',
            name='semester',
            field=models.CharField(default='N/A', max_length=6),
        ),
        migrations.AddField(
            model_name='section_t',
            name='year',
            field=models.CharField(default='N/A', max_length=4),
        ),
    ]
