# Generated by Django 3.2.8 on 2021-12-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom_T',
            fields=[
                ('roomID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('roomCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_T',
            fields=[
                ('courseID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('creditHour', models.IntegerField()),
                ('semester', models.CharField(max_length=6)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department_T',
            fields=[
                ('deptCode', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_T',
            fields=[
                ('facultyID', models.IntegerField(primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School_T',
            fields=[
                ('schoolTitle', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section_T',
            fields=[
                ('sectionNo', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('noOfEnrolledStudent', models.IntegerField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('day', models.CharField(max_length=4)),
                ('blocked', models.CharField(max_length=4)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seas.course_t')),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seas.faculty_t')),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seas.classroom_t')),
            ],
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AddField(
            model_name='department_t',
            name='schoolTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seas.school_t'),
        ),
        migrations.AddField(
            model_name='course_t',
            name='deptcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seas.department_t'),
        ),
    ]
