# Generated by Django 3.2.9 on 2021-12-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seas', '0002_auto_20211202_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_t',
            old_name='deptcode',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='department_t',
            old_name='schoolTitle',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='section_t',
            old_name='courseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='section_t',
            old_name='facultyID',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='section_t',
            old_name='roomID',
            new_name='room',
        ),
    ]
