# Generated by Django 3.2.9 on 2021-12-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seas', '0002_auto_20211209_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_t',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='section_t',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.DeleteModel(
            name='Faculty_T',
        ),
    ]
