# Generated by Django 3.2.9 on 2021-12-10 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seas', '0005_auto_20211210_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_t',
            name='endTime',
            field=models.TimeField(default=datetime.time(17, 14, 57, 236237)),
        ),
        migrations.AlterField(
            model_name='section_t',
            name='startTime',
            field=models.TimeField(default=datetime.time(17, 14, 57, 236226)),
        ),
    ]
