# Generated by Django 3.2.9 on 2021-12-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seas', '0006_auto_20211210_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_t',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='section_t',
            name='startTime',
        ),
    ]
